check:
  # Add checks here; list:
  # https://github.com/bridgecrewio/checkov/blob/master/docs/5.Policy%20Index/all.md
  # - CKV_AWS_1
  # - ...
compact: true
download-external-modules: true 
framework: terraform
output: cli 
quiet: true
soft-fail: false
